export const GET_PRODUCTS = 'GET_PRODUCT'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCT_FAILURE'

export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS'
export const GET_PRODUCT_BY_ID_FAILURE = 'GET_PRODUCT_BY_ID_FAILURE'
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_CLEAR_ITEM = 'CART_CLEAR_ITEM'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
export const USER_LOGOUT = 'USER_LOGOUT'

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

export const USER_REGISTER ='USER_REGISTER'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'

export const USER_DETAILS_FETCH ='USER_DETAILS_FETCH'
export const USER_DETAILS_FETCH_SUCCESS ='USER_DETAILS_FETCH_SUCCESS'
export const USER_DETAILS_FETCH_FAILURE ='USER_DETAILS_FETCH_FAILURE'


export const USER_UPDATE = 'USER_UPDATE'
export const USER_UPDATE_SUCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE'


