export const GET_PRODUCTS = 'GET_PRODUCT'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCT_FAILURE'

export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS'
export const GET_PRODUCT_BY_ID_FAILURE = 'GET_PRODUCT_BY_ID_FAILURE'
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'

